### ISSUE TITLE
Sending an empty id within the DELETE action can result in an error

### ISSUE THREAD

**Issue by jbreek** [Tools4everBV/HelloID-Conn-Prov-Target-RAET-IAM-API#1]
$account = [PSCustomObject]@{   
    displayName = $p.DisplayName
    externalId  = $aRef
    identity    = "" # empty because at the revoke action we want to clear the unique fields
}

Can result in an error within the DELETE action. 

"Error updating RAET user with employeeId 'xxxxx'. Current identity: prefix@suffix.nl. New identity: . Error Message: {"type":"[https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One](https://tools.ietf.org/html/rfc7231#section-6.5.1%22,%22title%22:%22One) or more validation errors occurred.","status":400,"traceId":"<some-guid>","errors":{"Id":["The Id field is required."]}}"

Possible solution might be to use '$null' instead of "", but isn't tested yet! Not clear if $null is accepted or a valid mailaddress is needed as an identity.

**Comment by rhouthuijzen** [comment]
@jbreek is this already tested? Then I can add this in the PSv2

**Comment by jbreek** [comment]
@rhouthuijzen don't really know. Been awhile since noted.

**Comment by rhouthuijzen** [comment]
Ok then I will link the issue to the new PSv2 branch. We can change the mapping there if needed.

**Comment by rhouthuijzen** [comment]
@jbreek  tested at custommer. Your solution gives back the following error:
Error at Line '250': $updatedAccount = Invoke-RestMethod @splatWebRequest -Verbose:$false . Error: {"type":"Argument Type Exception","title":"Argument is not of the expected type.","status":400,"detail":" has an invald identity format","traceId":"00-73301c161feb7d98df07edd4e5e3350a-4c18cdd4b2618da7-00"}

I fixed this by using externalID@domain.com

Will add this to the default mapping.
